baseURL = "https://StarianHK.github.io/"
title = "星學匯 Starian"
defaultContentLanguage = "zh-tw"
languageCode = "zh-tw"
timeZone = "Asia/Hong_Kong"
theme = "hugo-saasify-theme"

enableEmoji = true
enableGitInfo = true

[taxonomies]
  category = "categories"
  tag = "tags"

paginate = 9
paginatePath = "page"

[params]
  description = "星學匯致力連結內地港生與香港青年，提供升學、就業與交流平台。"
  author = "星學匯"
  logo = "/images/logo.png"

  [params.social]
    facebook = ""
    instagram = ""
    youtube = ""
    telegram = ""

  [params.footer]
    column_1_title = "關於我們"
    column_2_title = "活動資訊"
    column_3_title = "聯絡與政策"

  [params.header]
    background = "site-header-blue"
    border = "site-header-border"

    [params.header.logo]
      src = "/images/logo.png"
      class = "h-12"

    [params.header.menu]
      spacing = "space-x-8"
      linkClass = "site-header-link"
      mobileLinkClass = "site-mobile-link"

  [params.cta]
    enable = false

  [params.blog]
    enable = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ["^HUGO_", "^CI$"]

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[menu]
  [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "協會概況"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "近期活動"
    url = "/events/"
    weight = 3

  [[menu.main]]
    name = "加入我們"
    url = "/contact/"
    weight = 4

  [[menu.footer_column_1]]
    name = "協會概況"
    url = "/about/"
    weight = 1

  [[menu.footer_column_1]]
    name = "加入我們"
    url = "/contact/"
    weight = 2

  [[menu.footer_column_2]]
    name = "近期活動"
    url = "/events/"
    weight = 1

  [[menu.footer_column_2]]
    name = "活動 RSS"
    url = "/events/index.xml"
    weight = 2

  [[menu.footer_column_3]]
    name = "隱私政策"
    url = "/privacy/"
    weight = 1